<?php require_once("template/header.phtml"); ?>
<div class = "container">
    <div class = "row justify-content-center">
        <h2>Here you can add information to the database</h2>
    </div>
    <ul class="nav nav-pills mb-3 justify-content-center" id="pills-tab" role="tablist">
        <li class="nav-item">
            <?php
                if(isset($_COOKIE["currentPage"]))
                    if($_COOKIE["currentPage"] == "WorkDomPage")
                    {
                        echo '<a class="nav-link active" id = "workDomAddPill" data-toggle="pill" href="#addWorkDom" role="tab" aria-controls="addWorkDom" aria-selected="true">Add Work Domain </a>';
                    }
                    else
                    {
                        echo '<a class="nav-link" id = "workDomAddPill" data-toggle="pill" href="#addWorkDom" role="tab" aria-controls="addWorkDom" aria-selected="false">Add Work Domain </a>';
                    }
                else
                {
                    echo '<a class="nav-link active" id = "workDomAddPill" data-toggle="pill" href="#addWorkDom" role="tab" aria-controls="addWorkDom" aria-selected="true">Add Work Domain </a>';
                }
                    ?>

        </li>
        <li class="nav-item">
            <?php
            if(isset($_COOKIE["currentPage"]))
                if($_COOKIE["currentPage"] == "AssessmentTypePage")
                {
                    echo '<a class="nav-link active" id = "assTypeAddPill" data-toggle="pill" href="#addAssType" role="tab" aria-controls="addAssType" aria-selected="true">Add Assessment Types</a> ';
                }
                else
                {
                    echo '<a class="nav-link" id = "assTypeAddPill" data-toggle="pill" href="#addAssType" role="tab" aria-controls="addAssType" aria-selected="false">Add Assessment Types</a>';
                }
            else
            {
                echo '<a class="nav-link" id = "assTypeAddPill" data-toggle="pill" href="#addAssType" role="tab" aria-controls="addAssType" aria-selected="false">Add Assessment Types</a>';
            }
                ?>
        </li>
        <li class="nav-item">
            <?php
            if(isset($_COOKIE["currentPage"]))
                if($_COOKIE["currentPage"] == "SectionPage")
                {
                    echo '<a class="nav-link active" id = "sectionAddPill" data-toggle="pill" href="#addSection" role="tab" aria-controls="addSection" aria-selected="true">Add Sections</a>';
                }
                else
                {
                    echo '<a class="nav-link" id = "sectionAddPill" data-toggle="pill" href="#addSection" role="tab" aria-controls="addSection" aria-selected="false">Add Sections</a>';
                }
            else
            {
                echo '<a class="nav-link" id = "sectionAddPill" data-toggle="pill" href="#addSection" role="tab" aria-controls="addSection" aria-selected="false">Add Sections</a>';
            }
            ?>
        </li>
        <li class="nav-item">
            <?php
            if(isset($_COOKIE["currentPage"]))
                if($_COOKIE["currentPage"] == "QuestionPage")
                {
                    echo '<a class="nav-link active" id = "questionAddPill" data-toggle="pill" href="#addQuestion" role="tab" aria-controls="addQuestion" aria-selected="true">Add Questions</a>';
                }
                else
                {
                    echo '<a class="nav-link" id = "questionAddPill" data-toggle="pill" href="#addQuestion" role="tab" aria-controls="addQuestion" aria-selected="false">Add Questions</a>';
                }
            else
            {
                echo '<a class="nav-link" id = "questionAddPill" data-toggle="pill" href="#addQuestion" role="tab" aria-controls="addQuestion" aria-selected="false">Add Questions</a>';
            }
            ?>

        </li>
    </ul>

    <!--  Add Work Domain -->
    <div class="tab-content" id="pills-tabContent">
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "WorkDomPage")
            {
                echo '<div class="tab-pane fade show active" id="addWorkDom" role="tabpanel" aria-labelledby="workDomAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addWorkDom" role="tabpanel" aria-labelledby="workDomAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade show active" id="addWorkDom" role="tabpanel" aria-labelledby="workDomAddPill">';
        }
        ?>
            <form class="form-inline" method = "post" action="../addToDatabaseAdmin.php">
                <label for="workDomToAdd">Work Domain Name: </label>
                <input class="form-control" type="text" name = "workDomToAdd" placeholder="Work Domain Name">
                <button type="submit" name = "addWorkDom" class="btn btn-primary">Add</button>
            </form>
        </div>

        <!--  Add Assessment Type -->
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "AssessmentTypePage")
            {
                echo '<div class="tab-pane fade show active" id="addAssType" role="tabpanel" aria-labelledby="assTypeAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addAssType" role="tabpanel" aria-labelledby="assTypeAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" id="addAssType" role="tabpanel" aria-labelledby="assTypeAddPill">';
        }
            ?>
            <form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                <p>In order to add an assessment type please specify which work domain you would like to add the assessment type for</p>
                <label>Work Domains: </label>
                <select name="workDom" multiple class="form-control">
                    <?php
                    foreach($view->dom as $currentDomain)
                    {
                        echo '<option>'.$currentDomain->getDomain(). '</option>';
                    }
                    ?>
                </select>
                <label for="assTypeToAddName">Assessment Type Name: </label>
                <input class="form-control" type="text" name = "assTypeToAddName" placeholder="Assessment Type Name">
                <label for="assTypeToAddDesc">Assessment Type Description: </label>
                <textarea class="form-control" id="assTypeToAddDesc" rows="2"></textarea>
                <button type="submit" name = "addAssessmentType" class="btn btn-primary">Add</button>
            </form>
        </div>

        <!-- Add Section -->
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "SectionPage")
            {
                echo '<div class="tab-pane fade show active" id="addSection" role="tabpanel" aria-labelledby="sectionAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addSection" role="tabpanel" aria-labelledby="sectionAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" id="addSection" role="tabpanel" aria-labelledby="sectionAddPill">';
        }
        ?>
            <!-- Work domain Select -->
            <?php
                if(isset($_COOKIE["workDomSelected"]))
                {
                   echo '<form class="form-group d-none" method = "post" action="../addToDatabaseAdmin.php">';
                }
                else
                {
                    echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">';
                }
            ?>
                <label>In order to add a section please specify the work domain</label>
                <select name = "workDomNameSect" multiple class="form-control">
                    <?php
                    foreach($view->dom as $currentDomain)
                    {
                        echo '<option>'.$currentDomain->getDomain(). '</option>';
                    }
                    ?>
                </select>
                <button type="submit" name = "selectWorkDomain" class="btn btn-primary">Select Work Domain</button>
            </form>

            <!-- Assessment Type Select -->
            <?php
            if(isset($_COOKIE["workDomSelected"]) and !isset($_COOKIE["assessmentTypeSelected"]))
            {
                echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">';
            }
            else
            {
                echo '<form class="form-group d-none" method = "post" action="../addToDatabaseAdmin.php">';
            }
            ?>
                <label>And please specify the assessment type</label>
                <select name = "selectAssessmentTypeName" multiple class="form-control">
                    <?php
                    foreach($view->assess as $currentAssessmentType)
                    {
                        echo '<option>'.$currentAssessmentType->getName(). '</option>';
                    }
                    ?>
                </select>
                <button type="submit" name = "selectAssessmentTypeSubmit" class="btn btn-primary">Select Assessment Type</button>
            </form>

            <!-- Max no of sections for this assessment -->
            <?php
            if(isset($_COOKIE["workDomSelected"]) and isset($_COOKIE["assessmentTypeSelected"]) and !isset($_COOKIE["maxNoOfSections"]))
            {
                echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">';
            }
            else
            {
                echo '<form class="form-group d-none" method = "post" action="../addToDatabaseAdmin.php">';
            }
            ?>
                <label for="maxSection">Maxmimum sections for this assessment type: </label>
                <input class="form-control" type="number" name = "maxSection" placeholder="Insert Maximum Sections Here">
                <button type="submit" name = "maxInsertSubmit" class="btn btn-primary">Insert Maximum sections</button>

            </form>

            <!-- Section Addition here -->
            <?php
            if(isset($_COOKIE["assessmentTypeSelected"]) and isset($_COOKIE["maxNoOfSections"]))
            {
                for($x=0;$x<$_COOKIE["maxNoOfSections"];$x++)
                {
                    $currentSect = $x + 1;
                    if(!isset($_SESSION["nameSection".$x]))
                    {
                        echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                                <label for="sectionName">Section '. $currentSect .' Name: </label>
                                <input class="form-control" type="text" name = "nameSection'. $x .'" placeholder="Section Name">
                                
                                <label>Max Score For Section '.$currentSect.'</label>
                                <input class="form-control" type="number" name = "maxScoreSection'. $x .'" placeholder="Max Score For Section">

                                <label for="sectionDesc">Section '. $currentSect .' Description: </label>
                                <textarea class="form-control" id="sectionDesc" name="descSection'. $x .'" rows="2"></textarea>
                                
                                <button type="submit" name = "addSection" class="btn btn-primary">Add</button>
                                </br>
                                </br>';
                    }
                    else
                    {
                        echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                                <label for="sectionName">Section '. $currentSect .' Name: </label>
                                <input class="form-control" type="text" name = "nameSection'. $x .'" placeholder="'.$_SESSION["currentSectionInfo".$x][0].'" readonly>
                                
                                <label>Max Score For Section '.$currentSect.'</label>
                                <input class="form-control" type="number" name = "maxScoreSection'. $x .'" placeholder="'.$_SESSION["currentSectionInfo".$x][1].'" readonly>

                                <label for="sectionDesc">Section '. $currentSect .' Description: </label>
                                <textarea class="form-control" id="sectionDesc" name="descSection'. $x .'" rows="2" placeholder="'.$_SESSION["currentSectionInfo".$x][2].'" readonly></textarea>      
                            
                                </br>
                                </br>';
                    }
                    $sectNameNo = count($_SESSION['sectionNames']);
                    if($x == $sectNameNo -1)
                    {
                        echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                                
                                </form>';
                    }

                }
            }
            ?>

        </div>

        <!-- Add Question -->
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "QuestionPage")
            {
                echo '<div class="tab-pane fade show active" id="addQuestion" role="tabpanel" aria-labelledby="questionAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addQuestion" role="tabpanel" aria-labelledby="questionAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" id="addQuestion" role="tabpanel" aria-labelledby="questionAddPill">';
        }
        ?>
            <form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                <p>In order to add questions please select the domain, assessment type and section of the question </p>

                <label>Work Domains:</label>
                <select name = "workDomNameQuestion" multiple class="form-control">
                    <?php
                    foreach($view->dom as $currentDomain)
                    {
                        if($currentDomain->getDomain() == $_SESSION["selectedForAddQuestion"][0])
                        {
                            echo '<option selected>'.$currentDomain->getDomain(). '</option>';
                        }
                        else
                        {
                            echo '<option>'.$currentDomain->getDomain(). '</option>';
                        }
                    }
                    ?>
                </select>

                <label> Assessment Types:</label>
                <select name = "assessmentTypeNameQuestion" multiple class="form-control">
                    <?php
                    foreach($view->assess as $currentAssessmentType)
                    {
                        if($currentAssessmentType->getName() == $_SESSION["selectedForAddQuestion"][1])
                        {
                            echo '<option selected>' . $currentAssessmentType->getName() . '</option>';
                        }
                        else
                        {
                            echo '<option>' . $currentAssessmentType->getName() . '</option>';
                        }
                    }
                    ?>
                </select>
                <label> Sections:</label>
                <select name = "SectionNameQuestion" multiple class="form-control">
                    <?php
                    foreach($view->sections as $currentSection)
                    {
                        if($currentSection->getName() == $_SESSION["selectedForAddQuestion"][2])
                        {
                            echo '<option selected>' . $currentSection->getName() . '</option>';
                        }
                        else
                        {
                            echo '<option>' . $currentSection->getName() . '</option>';
                        }
                    }
                    ?>
                </select>
                <label>Enter your Question</label>
                <textarea class="form-control" rows = "2" type="text" name = "questionToAdd" placeholder="Type Your Question here and press add"></textarea>
                <button type="submit" name = "addQuestion" class="btn btn-primary">Add</button>
            </form>
        </div>
</div>
<a href="../deleteCookies.php" class="btn btn-primary">Delete Cookies</a>




<?php require_once("template/footer.phtml"); ?>
