<?php require_once("template/header.phtml"); ?>
<div class = "container">
    <div class = "row justify-content-center">
        <h2>Here you can add information to the database</h2>
    </div>
    <ul class="nav nav-pills mb-3 justify-content-center" id="pills-tab" role="tablist">
        <li class="nav-item">
            <?php
                if(isset($_COOKIE["currentPage"]))
                    if($_COOKIE["currentPage"] == "WorkDomPage")
                    {
                        echo '<a class="nav-link active" id = "workDomAddPill" data-toggle="pill" href="#addWorkDom" role="tab" aria-controls="addWorkDom" aria-selected="true">Add Work Domain </a>';
                    }
                    else
                    {
                        echo '<a class="nav-link" id = "workDomAddPill" data-toggle="pill" href="#addWorkDom" role="tab" aria-controls="addWorkDom" aria-selected="false">Add Work Domain </a>';
                    }
                else
                {
                    echo '<a class="nav-link active" id = "workDomAddPill" data-toggle="pill" href="#addWorkDom" role="tab" aria-controls="addWorkDom" aria-selected="true">Add Work Domain </a>';
                }
                    ?>

        </li>
        <li class="nav-item">
            <?php
            if(isset($_COOKIE["currentPage"]))
                if($_COOKIE["currentPage"] == "delegatePage")
                {
                    echo '<a class="nav-link active" id = "delegateAddPill" data-toggle="pill" href="#addDelegate" role="tab" aria-controls="addDelegate" aria-selected="true">Add Delegates</a>';
                }
                else
                {
                    echo '<a class="nav-link" id = "delegateAddPill" data-toggle="pill" href="#addDelegate" role="tab" aria-controls="addDelegate" aria-selected="false">Add Delegates</a>';
                }
            else
            {
                echo '<a class="nav-link" id = "delegateAddPill" data-toggle="pill" href="#addDelegate" role="tab" aria-controls="addDelegate" aria-selected="false">Add Delegates</a>';
            }
            ?>

        </li>
        <li class="nav-item">
            <?php
            if(isset($_COOKIE["currentPage"]))
                if($_COOKIE["currentPage"] == "AssessmentTypePage")
                {
                    echo '<a class="nav-link active" id = "assTypeAddPill" data-toggle="pill" href="#addAssType" role="tab" aria-controls="addAssType" aria-selected="true">Add Assessment Types</a> ';
                }
                else
                {
                    echo '<a class="nav-link" id = "assTypeAddPill" data-toggle="pill" href="#addAssType" role="tab" aria-controls="addAssType" aria-selected="false">Add Assessment Types</a>';
                }
            else
            {
                echo '<a class="nav-link" id = "assTypeAddPill" data-toggle="pill" href="#addAssType" role="tab" aria-controls="addAssType" aria-selected="false">Add Assessment Types</a>';
            }
                ?>
        </li>
        <li class="nav-item">
            <?php
            if(isset($_COOKIE["currentPage"]))
                if($_COOKIE["currentPage"] == "SectionPage")
                {
                    echo '<a class="nav-link active" id = "sectionAddPill" data-toggle="pill" href="#addSection" role="tab" aria-controls="addSection" aria-selected="true">Add Sections</a>';
                }
                else
                {
                    echo '<a class="nav-link" id = "sectionAddPill" data-toggle="pill" href="#addSection" role="tab" aria-controls="addSection" aria-selected="false">Add Sections</a>';
                }
            else
            {
                echo '<a class="nav-link" id = "sectionAddPill" data-toggle="pill" href="#addSection" role="tab" aria-controls="addSection" aria-selected="false">Add Sections</a>';
            }
            ?>
        </li>
        <li class="nav-item">
            <?php
            if(isset($_COOKIE["currentPage"]))
                if($_COOKIE["currentPage"] == "QuestionPage")
                {
                    echo '<a class="nav-link active" id = "questionAddPill" data-toggle="pill" href="#addQuestion" role="tab" aria-controls="addQuestion" aria-selected="true">Add Questions</a>';
                }
                else
                {
                    echo '<a class="nav-link" id = "questionAddPill" data-toggle="pill" href="#addQuestion" role="tab" aria-controls="addQuestion" aria-selected="false">Add Questions</a>';
                }
            else
            {
                echo '<a class="nav-link" id = "questionAddPill" data-toggle="pill" href="#addQuestion" role="tab" aria-controls="addQuestion" aria-selected="false">Add Questions</a>';
            }
            ?>
        </li>
    </ul>

    <!--  Add Work Domain -->
    <div class="tab-content" id="pills-tabContent">
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "WorkDomPage")
            {
                echo '<div class="tab-pane fade show active" id="addWorkDom" role="tabpanel" aria-labelledby="workDomAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addWorkDom" role="tabpanel" aria-labelledby="workDomAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade show active" id="addWorkDom" role="tabpanel" aria-labelledby="workDomAddPill">';
        }
        ?>
            <form class="form-inline" method = "post" action="../addToDatabaseAdmin.php">
                <label for="workDomToAdd">Work Domain Name: </label>
                <input class="form-control" type="text" name = "workDomToAdd" placeholder="Work Domain Name" required>
                <button type="submit" name = "addWorkDom" class="btn btn-primary">Add</button>
            </form>
        </div>

        <!--  Add Assessment Type -->
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "AssessmentTypePage")
            {
                echo '<div class="tab-pane fade show active" id="addAssType" role="tabpanel" aria-labelledby="assTypeAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addAssType" role="tabpanel" aria-labelledby="assTypeAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" id="addAssType" role="tabpanel" aria-labelledby="assTypeAddPill">';
        }
            ?>
            <form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                <p>In order to add an assessment type please specify which work domain you would like to add the assessment type for</p>
                <label>Work Domains: </label>
                <select name="workDom" multiple class="form-control" required>
                    <?php
                    foreach($view->dom as $currentDomain)
                    {
                        echo '<option>'.$currentDomain->getDomain(). '</option>';
                    }
                    ?>
                </select>
                <label for="assTypeToAddName">Assessment Type Name: </label>
                <input class="form-control" type="text" name = "assTypeToAddName" placeholder="Assessment Type Name" required>
                <label for="assTypeToAddDesc">Assessment Type Description: </label>
                <textarea class="form-control" id="assTypeToAddDesc" rows="2" required></textarea>
                <button type="submit" name = "addAssessmentType" class="btn btn-primary">Add</button>
            </form>
        </div>

        <!-- Add Section -->
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "SectionPage")
            {
                echo '<div class="tab-pane fade show active" id="addSection" role="tabpanel" aria-labelledby="sectionAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addSection" role="tabpanel" aria-labelledby="sectionAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" id="addSection" role="tabpanel" aria-labelledby="sectionAddPill">';
        }
        ?>
            <!-- Work domain Select -->
            <?php
                if(isset($_COOKIE["workDomSelected"]))
                {
                   echo '<form class="form-group d-none" method = "post" action="../addToDatabaseAdmin.php">';
                }
                else
                {
                    echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">';
                }
            ?>
                <label>In order to add a section please specify the work domain</label>
                <select name = "workDomNameSect" multiple class="form-control" required>
                    <?php
                    foreach($view->dom as $currentDomain)
                    {
                        echo '<option>'.$currentDomain->getDomain(). '</option>';
                    }
                    ?>
                </select>
                <button type="submit" name = "selectWorkDomain" class="btn btn-primary">Select Work Domain</button>
            </form>

            <!-- Assessment Type Select -->
            <?php
            if(isset($_COOKIE["workDomSelected"]) and !isset($_COOKIE["assessmentTypeSelected"]))
            {
                echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">';
            }
            else
            {
                echo '<form class="form-group d-none" method = "post" action="../addToDatabaseAdmin.php">';
            }
            ?>
                <label>And please specify the assessment type</label>
                <select name = "selectAssessmentTypeName" multiple class="form-control" required>
                    <?php
                    foreach($view->assess as $currentAssessmentType)
                    {
                        echo '<option>'.$currentAssessmentType->getName(). '</option>';
                    }
                    ?>
                </select>
                <button type="submit" name = "selectAssessmentTypeSubmit" class="btn btn-primary">Select Assessment Type</button>
            </form>

            <!-- Max no of sections for this assessment -->
            <?php
            if(isset($_COOKIE["workDomSelected"]) and isset($_COOKIE["assessmentTypeSelected"]) and !isset($_COOKIE["maxNoOfSections"]))
            {
                echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">';
            }
            else
            {
                echo '<form class="form-group d-none" method = "post" action="../addToDatabaseAdmin.php">';
            }
            ?>
                <label for="maxSection">Maxmimum sections for this assessment type: </label>
                <input class="form-control" min = "1" max="10" type="number" name = "maxSection" placeholder="Insert Maximum Sections Here">
                <button type="submit" name = "maxInsertSubmit" class="btn btn-primary">Insert Maximum sections</button>

            </form>

            <!-- Section Addition here -->
            <?php
            if(isset($_COOKIE["assessmentTypeSelected"]) and isset($_COOKIE["maxNoOfSections"]))
            {
                for($x=0;$x<$_COOKIE["maxNoOfSections"];$x++)
                {
                    $currentSect = $x + 1;
                    if(!isset($_SESSION["nameSection".$x]))
                    {
                        echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                                <label for="sectionName">Section '. $currentSect .' Name: </label>
                                <input class="form-control" type="text" name = "nameSection'. $x .'" placeholder="Section Name">
                                
                                <label>Max Score For Section '.$currentSect.'</label>
                                <input class="form-control" type="number" name = "maxScoreSection'. $x .'" placeholder="Max Score For Section">

                                <label for="sectionDesc">Section '. $currentSect .' Description: </label>
                                <textarea class="form-control" id="sectionDesc" name="descSection'. $x .'" rows="2"></textarea>
                                
                                
                                </br>
                                </br>';
                    }
                    else
                    {
                        echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                                <label for="sectionName">Section '. $currentSect .' Name: </label>
                                <input class="form-control" type="text" name = "nameSection'. $x .'" placeholder="'.$_SESSION["currentSectionInfo".$x][0].'" readonly>
                                
                                <label>Max Score For Section '.$currentSect.'</label>
                                <input class="form-control" type="number" name = "maxScoreSection'. $x .'" placeholder="'.$_SESSION["currentSectionInfo".$x][1].'" readonly>

                                <label for="sectionDesc">Section '. $currentSect .' Description: </label>
                                <textarea class="form-control" id="sectionDesc" name="descSection'. $x .'" rows="2" placeholder="'.$_SESSION["currentSectionInfo".$x][2].'" readonly></textarea>      
                            
                                </br>
                                </br>';
                    }


                }
                $sectNameNo = count($_SESSION['sectionNames']);
                if($x == $sectNameNo -1)
                {
                    //echo '<form class="form-group" method = "post" action="../addToDatabaseAdmin.php">';
                    echo '<button type="submit" name = "addSections" class="btn btn-primary">Add Sections</button>';
                    echo '</form>';
                }
            }
            ?>

        </div>

        <!-- Add Question -->
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] === "QuestionPage")
            {
                echo '<div class="tab-pane fade show active" id="addQuestion" role="tabpanel" aria-labelledby="questionAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addQuestion" role="tabpanel" aria-labelledby="questionAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" id="addQuestion" role="tabpanel" aria-labelledby="questionAddPill">';
        }
        ?>
            <form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                <p>In order to add questions please select the domain, assessment type and section of the question </p>

                <label>Work Domains:</label>
                <select name = "workDomNameQuestion" multiple class="form-control" required>
                    <?php
                    foreach($view->dom as $currentDomain)
                    {
                        if($currentDomain->getDomain() === $_SESSION["selectedForAddQuestion"][0])
                        {
                            echo '<option value = "" selected>'.$currentDomain->getDomain(). '</option>';
                        }
                        else
                        {
                            echo '<option>'.$currentDomain->getDomain(). '</option>';
                        }
                    }
                    ?>
                </select>

                <label> Assessment Types:</label>
                <select name = "assessmentTypeNameQuestion" multiple class="form-control" required>
                    <?php
                    foreach($view->assess as $currentAssessmentType)
                    {
                        if($currentAssessmentType->getName() === $_SESSION["selectedForAddQuestion"][1])
                        {
                            echo '<option selected>' . $currentAssessmentType->getName() . '</option>';
                        }
                        else
                        {
                            echo '<option>' . $currentAssessmentType->getName() . '</option>';
                        }
                    }
                    ?>
                </select>
                <label> Sections:</label>
                <select name = "SectionNameQuestion" multiple class="form-control" required>
                    <?php
                    $x = 0;

                    $sectionIDs = $view->sectionIDs;
                    foreach($view->sections as $currentSection)
                    {
                        $currentID = $sectionIDs[$x];
                        if((int)$currentID->getSectionID() === (int)$_SESSION["selectedForAddQuestion"][2])
                        {
                            echo '<option value = "'.$currentID->getSectionID().'" selected>' . $currentSection->getName() . '</option>';
                        }
                        else
                        {
                            echo '<option value = "'.$currentID->getSectionID().'">' . $currentSection->getName() . '</option>';
                        }
                        $x++;
                    }
                    ?>
                </select>
                <label>Enter your Question</label>
                <?php
                    if (isset($_COOKIE["questionToAdd"]))
                    {
                        if(!empty($_COOKIE["questionToAdd"]))
                        {
                            echo '<textarea class="form-control" rows = "2" type="text" name = "questionToAdd" readonly>'.$_COOKIE["questionToAdd"].'</textarea>';
                        }
                        else
                        {
                            echo '<textarea class="form-control" rows = "2" type="text" name = "questionToAdd" placeholder="Type Your Question here and press add" required></textarea>';
                            echo '<button type="submit" name = "addQuestion" class="btn btn-primary">Add</button>';
                        }
                    }
                    else
                    {
                        echo '<textarea class="form-control" rows = "2" type="text" name = "questionToAdd" placeholder="Type Your Question here and press add" required></textarea>';
                        echo '<button type="submit" name = "addQuestion" class="btn btn-primary">Add</button>';
                    }
                ?>
            </form>
            <?php
            if(isset($_COOKIE["questionToAdd"]))
                if(!empty($_COOKIE["questionToAdd"]))
                {
                    echo '<div class="tab-pane fade show active" role="tabpanel" aria-labelledby="questionAddPill">';
                }
                else
                {
                    echo '<div class="tab-pane fade" role="tabpanel" aria-labelledby="questionAddPill">';
                }
            else
            {
                echo '<div class="tab-pane fade" role="tabpanel" aria-labelledby="questionAddPill">';
            }
            ?>
            <form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                <label>Enter the max Score For Question: </label>
                <?php
                if(isset($_COOKIE["maxScore"]))
                {
                    if(!empty($_COOKIE["maxScore"]))
                    {
                        echo '<input class="form-control" type="number" name = "maxScoreQuestion" placeholder="'.$_COOKIE["maxScore"].'" readonly>';
                    }
                    else
                    {
                        echo '<input class="form-control" min = "1" max = "10" type="number" name = "maxScoreQuestion" placeholder="please enter the max score here" required>';
                        echo '<button type="submit" name = "maxScore" class="btn btn-primary">Enter The maximum Score</button>';
                    }
                }
                else
                {
                    echo '<input class="form-control" min = "1" max = "10" type="number" name = "maxScoreQuestion" placeholder="please enter the max score here" required>';
                    echo '<button type="submit" name = "maxScore" class="btn btn-primary">Enter The maximum Score</button>';
                }
                ?>
            </form>
        </div>
        <?php
        if(isset($_COOKIE["maxScore"]))
            if(!empty($_COOKIE["maxScore"]))
            {
                echo '<div class="tab-pane fade show active" role="tabpanel" aria-labelledby="questionAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" role="tabpanel" aria-labelledby="questionAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" role="tabpanel" aria-labelledby="questionAddPill">';
        }
        ?>
            <form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                <?php
                    if(!empty($_COOKIE["maxScore"]))
                    {
                        for($x=0;$x<$_COOKIE["maxScore"];$x++)
                        {
                            $userScore = $x +1;
                            echo '<label>Indicator Score:</label>';
                            echo '<input class="form-control" type="number" name = "indicatorScore'.$x.'" value = "'.$userScore.'" readonly>';
                            echo '<label>Please Enter the indicator description for the assessor</label>';
                            echo '<input class="form-control" type="text" name = "indicatorName'.$x.'" placeholder="please enter indicator description for the assessor here">';
                            echo '<label>Please Enter the indicator description for the auto-generated feedback</label>';
                            echo '<input class="form-control" type="text" name = "indicatorFeedback'.$x.'" placeholder="please enter indicator feedback here">';
                            echo '</br>';
                            echo '</br>';
                        }
                    }
                ?>
                <button type="submit" id = "finishBindicatorsForQuestions" name = "addIndicator" class="btn btn-primary mb-5">Finish</button>
            </form>
        </div>
    </div>
    <!-- Add delegate -->
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "delegatePage")
            {
                echo '<div class="tab-pane fade show active" id="addDelegate" role="tabpanel" aria-labelledby="delegateAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addDelegate" role="tabpanel" aria-labelledby="delegateAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" id="addDelegate" role="tabpanel" aria-labelledby="delegateAddPill">';
        }
        ?>
        <form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
            <label>Please Select The candidate's work domain</label>
            <select name = "workDomForCandid" multiple class="form-control" required>
                <?php
                foreach($view->dom as $currentDomain)
                {
                    echo '<option>'.$currentDomain->getDomain(). '</option>';
                }
                ?>
            </select>
            <label>
                Candidate Name:
            </label>
            <input class="form-control" type="text" name = "candidateName" placeholder="please enter candidate name here" required>
            <label>
                Candidate E-mail:
            </label>
            <input class="form-control" type="email" name = "candidateEmail" placeholder="please enter candidate e-mai here" required>
            <button type="submit" name = "addDelegate" class="btn btn-primary">Add</button>
        </form>
    </div>
</div>




<?php require_once("template/footer.phtml"); ?>
