<?php require_once("template/header.phtml"); ?>
<div class = "container">
    <div class = "row justify-content-center">
        <h2>Here you can add information to the database</h2>
    </div>
    <ul class="nav nav-pills mb-3 justify-content-center" id="pills-tab" role="tablist">
        <li class="nav-item">
            <?php
                if(isset($_COOKIE["currentPage"]))
                    if($_COOKIE["currentPage"] == "WorkDomPage")
                    {
                        echo '<a class="nav-link active" id = "workDomAddPill" data-toggle="pill" href="#addWorkDom" role="tab" aria-controls="addWorkDom" aria-selected="true">Add Work Domain </a>';
                    }
                    else
                    {
                        echo '<a class="nav-link" id = "workDomAddPill" data-toggle="pill" href="#addWorkDom" role="tab" aria-controls="addWorkDom" aria-selected="false">Add Work Domain </a>';
                    }
                else
                {
                    echo '<a class="nav-link active" id = "workDomAddPill" data-toggle="pill" href="#addWorkDom" role="tab" aria-controls="addWorkDom" aria-selected="true">Add Work Domain </a>';
                }
                    ?>

        </li>
        <li class="nav-item">
            <?php
            if(isset($_COOKIE["currentPage"]))
                if($_COOKIE["currentPage"] == "AssessmentTypePage")
                {
                    echo '<a class="nav-link active" id = "assTypeAddPill" data-toggle="pill" href="#addAssType" role="tab" aria-controls="addAssType" aria-selected="true">Add Assessment Types</a> ';
                }
                else
                {
                    echo '<a class="nav-link" id = "assTypeAddPill" data-toggle="pill" href="#addAssType" role="tab" aria-controls="addAssType" aria-selected="false">Add Assessment Types</a>';
                }
            else
            {
                echo '<a class="nav-link" id = "assTypeAddPill" data-toggle="pill" href="#addAssType" role="tab" aria-controls="addAssType" aria-selected="false">Add Assessment Types</a>';
            }
                ?>
        </li>
        <li class="nav-item">
            <?php
            if(isset($_COOKIE["currentPage"]))
                if($_COOKIE["currentPage"] == "SectionPage")
                {
                    echo '<a class="nav-link active" id = "sectionAddPill" data-toggle="pill" href="#addSection" role="tab" aria-controls="addSection" aria-selected="true">Add Sections</a>';
                }
                else
                {
                    echo '<a class="nav-link" id = "sectionAddPill" data-toggle="pill" href="#addSection" role="tab" aria-controls="addSection" aria-selected="false">Add Sections</a>';
                }
            else
            {
                echo '<a class="nav-link" id = "sectionAddPill" data-toggle="pill" href="#addSection" role="tab" aria-controls="addSection" aria-selected="false">Add Sections</a>';
            }
            ?>
        </li>
        <li class="nav-item">
            <?php
            if(isset($_COOKIE["currentPage"]))
                if($_COOKIE["currentPage"] == "QuestionPage")
                {
                    echo '<a class="nav-link active" id = "questionAddPill" data-toggle="pill" href="#addQuestion" role="tab" aria-controls="addQuestion" aria-selected="true">Add Questions</a>';
                }
                else
                {
                    echo '<a class="nav-link" id = "questionAddPill" data-toggle="pill" href="#addQuestion" role="tab" aria-controls="addQuestion" aria-selected="false">Add Questions</a>';
                }
            else
            {
                echo '<a class="nav-link" id = "questionAddPill" data-toggle="pill" href="#addQuestion" role="tab" aria-controls="addQuestion" aria-selected="false">Add Questions</a>';
            }
            ?>

        </li>
    </ul>

    <!--  Add Work Domain -->
    <div class="tab-content" id="pills-tabContent">
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "WorkDomPage")
            {
                echo '<div class="tab-pane fade show active" id="addWorkDom" role="tabpanel" aria-labelledby="workDomAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addWorkDom" role="tabpanel" aria-labelledby="workDomAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade show active" id="addWorkDom" role="tabpanel" aria-labelledby="workDomAddPill">';
        }
        ?>
            <form class="form-inline" method = "post" action="../addToDatabaseAdmin.php">
                <label for="workDomToAdd">Work Domain Name: </label>
                <input class="form-control" type="text" name = "workDomToAdd" placeholder="Work Domain Name">
                <button type="submit" name = "addWorkDom" class="btn btn-primary">Add</button>
            </form>
        </div>

        <!--  Add Assessment Type -->
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "AssessmentTypePage")
            {
                echo '<div class="tab-pane fade show active" id="addAssType" role="tabpanel" aria-labelledby="assTypeAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addAssType" role="tabpanel" aria-labelledby="assTypeAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" id="addAssType" role="tabpanel" aria-labelledby="assTypeAddPill">';
        }
            ?>
            <form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                <label>In order to add an assessment type please specify which work domain you would like to add the assessment type for</label>
                <select name="workDom" multiple class="form-control">
                    <?php
                    foreach($view->dom as $currentDomain)
                    {
                        echo '<option>'.$currentDomain->getDomain(). '</option>';
                    }
                    ?>
                </select>
                <label for="assTypeToAddName">Assessment Type Name: </label>
                <input class="form-control" type="text" name = "assTypeToAddName" placeholder="Assessment Type Name">
                <label for="assTypeToAddDesc">Assessment Type Description: </label>
                <textarea class="form-control" id="assTypeToAddDesc" rows="2"></textarea>
                <button type="submit" name = "addAssessmentType" class="btn btn-primary">Add</button>
            </form>
        </div>

        <!-- Add Section -->
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "SectionPage")
            {
                echo '<div class="tab-pane fade show active" id="addSection" role="tabpanel" aria-labelledby="sectionAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addSection" role="tabpanel" aria-labelledby="sectionAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" id="addSection" role="tabpanel" aria-labelledby="sectionAddPill">';
        }
        ?>
            <form class="form-group" method = "post" action="../addToDatabaseAdmin.php">
                <label>In order to add a section please specify the work domain</label>
                <select name = "workDomNameSect" multiple class="form-control">
                    <?php
                    foreach($view->dom as $currentDomain)
                    {
                        echo '<option>'.$currentDomain->getDomain(). '</option>';
                    }
                    ?>
                </select>
                <label>And please specify the assessment type</label>

                <select name = "assessmentTypeName" multiple class="form-control">
                    <?php
                    foreach($view->a as $currentDomain)
                    {
                        echo '<option>'.$currentDomain->getDomain(). '</option>';
                    }
                    ?>
                </select>
                <label for="assTypeToAddName">Assessment Type Name: </label>
                <input class="form-control" type="text" name = "assTypeToAddName" placeholder="Assessment Type Name">
                <label for="assTypeToAddDesc">Assessment Type Description: </label>
                <textarea class="form-control" id="assTypeToAddDesc" rows="2"></textarea>
                <button type="submit" name = "addSection" class="btn btn-primary">Add</button>
            </form>
        </div>

        <!-- Add Question -->
        <?php
        if(isset($_COOKIE["currentPage"]))
            if($_COOKIE["currentPage"] == "QuestionPage")
            {
                echo '<div class="tab-pane fade show active" id="addQuestion" role="tabpanel" aria-labelledby="questionAddPill">';
            }
            else
            {
                echo '<div class="tab-pane fade" id="addQuestion" role="tabpanel" aria-labelledby="questionAddPill">';
            }
        else
        {
            echo '<div class="tab-pane fade" id="addQuestion" role="tabpanel" aria-labelledby="questionAddPill">';
        }
        ?>
        <div class="tab-pane fade" id="addQuestion" role="tabpanel" aria-labelledby="questionAddPill">
            <button type="submit" name = "addQuestion" class="btn btn-primary">Add</button>
        </div>
</div>
<a href="../fuckTheCookies.php" class="btn btn-primary">Delete Cookies</a>




<?php require_once("template/footer.phtml"); ?>
