<?php require('template/header.phtml') ?>
<div class = "container">
    <h2>Add info to database</h2>
    <?php
    if(!empty($_COOKIE["workDomName"]))
    {
        echo '<div class = "d-none" id = "workDomain">';
    }
    else
    {
        echo '<div id = "workDomain">';
    }

    ?>
        <form class="form-group" method = "post" action="../addToDatabase.php">
            <label for="sections">Select Or Add Work Domain</label>
            <input class="form-control" type="text" name = "workDomToAdd" placeholder="Insert Work Domain If wanted">
            <select name = "workDomName" multiple class="form-control">
                <?php
                    foreach($view->dom as $currentDomain)
                    {
                        echo '<option>'.$currentDomain->getDomain(). '</option>';
                    }
                ?>
            </select>
            <button type="submit" name = "submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <?php
        if(!empty($_COOKIE["workDomName"]) and empty($_COOKIE["assessmentTypeName"]))
        {
            echo '<div id = "assessmentType">';
            echo '<h2>Work Domain : '.$_COOKIE["workDomName"].'</h2>';
        }
        else
        {
            echo '<div class = "d-none" id = "assessmentType">';
        }

    ?>
        <form class="form-group" method = "post" action="../addToDatabase.php">
            <label for="sections">Select Or Add Assessment Type</label>
            <input class="form-control" type="text" name = "assTypeToAdd" placeholder="Insert new Assessment Type Here if wanted">
            <select name = "assessmentType" multiple class="form-control">
                <?php
                foreach($view->assess as $currentAss)
                {
                    echo '<option>'.$currentAss->getName(). '</option>';
                }
                ?>
            </select>
            <input class="form-control" type="text" name = "assTypeDesc" placeholder="Add a brief Description here">
            <button type="submit" name = "submit" class="btn btn-primary">Submit</button>
        </form>
     </div>
    <?php
    if(!empty($_COOKIE["assessmentTypeName"]) and empty($_COOKIE["sectionName"]))
    {
        echo '<div id = "section">';
        echo '<h2>Work Domain : '.$_COOKIE["workDomName"].'</h2>';
        echo '<h3>Assessment Type : '.$_COOKIE["assessmentTypeName"].'</h3>';

    }
    else
    {
        echo '<div class = "d-none" id = "section">';
    }

    ?>
        <form class="form-group" method = "post" action="../addToDatabase.php">
            <label for="sections">Select Or Add Secion name</label>
            <input class="form-control" type="text" name = "sectionName" placeholder="Insert new Section name here if wanted">
            <select name = "section" multiple class="form-control">
                <?php
                foreach($view->sections as $currentSection)
                {
                    echo '<option>'.$currentSection->getName(). '</option>';
                }
                ?>
            </select>
            <input class="form-control" type="text" name = "sectionDesc" placeholder="Add a brief Description here">
            <button type="submit" name = "submit" class="btn btn-primary">Submit</button>
        </form>

        </div>
        <?php
        if(!empty($_COOKIE["sectionName"]) and empty($_COOKIE["maxQuestion"]) and empty($_COOKIE["maxScore"]))
        {
            echo '<div id = "max">';
            echo '<h2>Work Domain : '.$_COOKIE["workDomName"].'</h2>';
            echo '<h3>Assessment Type : '.$_COOKIE["assessmentTypeName"].'</h3>';
            echo '<h4>Section : '.$_COOKIE["sectionName"].'</h4>';
        }
        else
        {
            echo '<div class = "d-none" id = "max">';
        }

        ?>
            <form class="form-group" method = "post" action="../addToDatabase.php">
                <label for="max">Select Max Number Of Questions and Max Score</label>
                <input class="form-control" type="number" name = "maxQuestion" placeholder="Enter here the maximum number of questions">
                <input class="form-control" type="number" name = "maxScore" placeholder="Enter here the maximum score">
                <button type="submit" name = "submit" class="btn btn-primary">Submit</button>
            </form>
            </div>



        <?php
        if(!empty($_COOKIE["maxQuestion"]) and !empty($_COOKIE["maxScore"]) and empty($_COOKIE["question"]))
        {
            echo '<div id = "questions">';
            echo '<h2>Work Domain : '.$_COOKIE["workDomName"].'</h2>';
            echo '<h3>Assessment Type : '.$_COOKIE["assessmentTypeName"].'</h3>';
            echo '<h4>Section : '.$_COOKIE["sectionName"].'</h4>';
        }
        else
        {
            echo '<div class = "d-none" id = "questions">';
        }

        ?>
            <form class="form-group" method = "post" action="../addToDatabase.php">
                <?php
                    for($x=0;$x<$_COOKIE["maxQuestion"];$x++)
                    {
                        echo '<input class="form-control" list="questionsToChoose'.$x.'" name="question'.$x.'"/>';
                        echo '<datalist id="questionsToChoose'.$x.'">';
                        foreach($view->questions as $currentQuestion)
                        {
                            echo  "<option>".$currentQuestion->getQuestion()."</option>";
                        }
                        echo '</datalist>';
                    }
                ?>
            </form>
            <button type="submit" name = "submit" class="btn btn-primary">Submit</button>
        </div>
    <a href="../deleteCookies.php" class="btn btn-primary">Delete Cookies</a>


<?php require('template/footer.phtml') ?>