<?php require_once("template/header.phtml"); ?>
<div class = "container">
    <div class = "row justify-content-center">
        <h2>Here you can mark a candidate</h2>
    </div>
        <?php
            if(!empty($_COOKIE["candNameAssessor"]))
            {
                echo '<div class = "d-none">';
            }
            else
            {
                echo '<div>';
            }
        ?>
        <form class="form-group" method = "post" action="../assessorView.php">
            <label>Please enter candidate's name to search through all candidates</label>
            <input class="form-control" type="text" name = "candNameAssessor" placeholder="Please Enter candidate name">
            <button type="submit" name = "search" class="btn btn-primary">Search</button>
        </form>
    </div>
        <?php
        if(isset($_COOKIE["candNameAssessor"]) and !isset($_COOKIE["selectedAssessmentType"]))
        {
            if(!empty($_COOKIE["candNameAssessor"]))
            {
                echo '<div>';
            }
            else
            {
                echo '<div class = "d-none">';
            }
        }
        else
        {
            echo '<div class = "d-none">';
        }
        ?>
        <form class="form-group" method = "post" action="../assessorView.php">
            <label> Assessment Types For candidate:</label>
            <select name = "assessmentTypes" multiple class="form-control">
                <?php
                foreach($_SESSION["assessmentTypeNames"] as $currentType)
                {
                    echo '<option>'.$currentType. '</option>';
                }
                ?>
            </select>
            <button type="submit" name = "selectedAssessmentType" class="btn btn-primary">Select Assessment Type</button>
        </form>
    </div>
    <?php
    if(isset($_COOKIE["selectedAssessmentType"]))
    {
        if(!empty($_COOKIE["selectedAssessmentType"]))
        {
            echo '<div>';
        }
        else
        {
            echo '<div class = "d-none">';
        }
    }
    else
    {
        echo '<div class = "d-none">';
    }
    ?>
        <h3>Section 1 : Motivation</h3>
        <h4 style="font-style: italic;">Question their motivation, level of interest and any preconceptions that they
            have. You may find the following prompt questions useful:</h4>
        <ul>
            <li>Tell us about why you are interested in working in this environment?</li>
            <li>What qualities do you feel will make you a success?</li>
            <li>Is there anything that worries you about working for the Government
                (insert chosen field i.e., Engineer, Medical, HR)?
            <li>What are you looking to achieve in your career?</li>
        </ul>
        <div class = "container">
            <div class = "row justify-content-center">
                <div class="col-3">
                    Lack of understanding of what
                    the role involves; makes
                    unfounded assumptions about
                    the role
                </div>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-secondary" data-toggle="collapse" data-target="#row1" aria-controls="collapseExample">
                        <input type="radio" name="options" id="option1" autocomplete="off"> 1
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option2" autocomplete="off"> 2
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option3" autocomplete="off"> 3
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option4" autocomplete="off"> 4
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option5" autocomplete="off"> 5
                    </label>
                </div>
                <div class="col-3">
                    Shows a clear understanding of
                    the role, demonstrates passion
                    for their chosen area
                </div>
            </div>
            <div class="row justify-content-center collapse" id="row1">
                <div class="card card-body col-4">
                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
                </div>
            </div>
            <div class = "row justify-content-center">
                <div class="col-3">
                    Demonstrates limited/no
                    personal motivation for the
                    role
                </div>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-secondary active">
                        <input type="radio" name="options" id="option1" autocomplete="off"> 1
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option2" autocomplete="off"> 2
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option3" autocomplete="off"> 3
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option4" autocomplete="off"> 4
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option5" autocomplete="off"> 5
                    </label>
                </div>
                <div class="col-3">
                    Provides strong personal
                    motivation for the role
                </div>
            </div>
            <div class = "row justify-content-center">
                <div class="col-3">
                    Limited consideration of their
                    personal fit with the role
                </div>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-secondary active">
                        <input type="radio" name="options" id="option1" autocomplete="off"> 1
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option2" autocomplete="off"> 2
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option3" autocomplete="off"> 3
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option4" autocomplete="off"> 4
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option5" autocomplete="off"> 5
                    </label>
                </div>
                <div class="col-3">
                    Demonstrates their personal fit
                    (skills, qualities and
                    experiences) for the role
                </div>
            </div>
            <div class = "row justify-content-center">
                <div class="col-3">
                    Speaks in a hesitant or
                    unconvincing manner;
                    displays a lack of confidence;
                    or speaks too fast and
                    mumbles
                </div>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-secondary active">
                        <input type="radio" name="options" id="option1" autocomplete="off"> 1
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option2" autocomplete="off"> 2
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option3" autocomplete="off"> 3
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option4" autocomplete="off"> 4
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="options" id="option5" autocomplete="off"> 5
                    </label>
                </div>
                <div class="col-3">
                    Speaks confidently and clearly
                    and at a good pace
                </div>
            </div>
        </div>
    </div>
    <a href="../deleteCookies.php" class="btn btn-primary">Delete Cookies</a>
</div>
<?php require_once("template/footer.phtml"); ?>
