<h3>Section 1 : Motivation</h3>
<h4 style="font-style: italic;">Question their motivation, level of interest and any preconceptions that they
    have. You may find the following prompt questions useful:</h4>
<ul>
    <li>Tell us about why you are interested in working in this environment?</li>
    <li>What qualities do you feel will make you a success?</li>
    <li>Is there anything that worries you about working for the Government
        (insert chosen field i.e., Engineer, Medical, HR)?
    <li>What are you looking to achieve in your career?</li>
</ul>
<br class = "container">
<div id = "question1">
    <div class = "row justify-content-center">
        <div class="col-3" style="border-bottom-style: solid;">
            Lack of understanding of what
            the role involves; makes
            unfounded assumptions about
            the role
        </div>
        <script src="../js/myscripts.js"></script>
        <form class="btn-group btn-group-toggle h-50" data-toggle="buttons" id = "q1">
            <label class="btn btn-secondary" data-toggle="collapse" data-target="#row1" aria-controls="row1">
                <input type="radio" name="options" id="option1" autocomplete="off" value = "1"> 1
            </label>
            <label class="btn btn-secondary" data-toggle="collapse" data-target="#row2" aria-controls="row2">
                <input type="radio" name="options" id="option2" autocomplete="off" value = "2"> 2
            </label>
            <label class="btn btn-secondary" data-toggle="collapse" data-target="#row3" aria-controls="row3">
                <input type="radio" name="options" id="option3" autocomplete="off" value = "3"> 3
            </label>
            <label class="btn btn-secondary" data-toggle="collapse" data-target="#row4" aria-controls="row4">
                <input type="radio" name="options" id="option4" autocomplete="off" value = "4"> 4
            </label>
            <label class="btn btn-secondary" data-toggle="collapse" data-target="#row5" aria-controls="row5">
                <input type="radio" name="options" id="option5" autocomplete="off"> 5
            </label>
        </form>
        <div class="col-3" style="border-bottom-style: solid;">
            Shows a clear understanding of
            the role, demonstrates passion
            for their chosen area
        </div>
    </div>
    <div class="row justify-content-center collapse" id="row1" data-parent="#question1">
        <div class="card card-body col-4">
            Here is what 1 means
        </div>
    </div>
    <div class="row justify-content-center collapse" id="row2" data-parent="#question1">
        <div class="card card-body col-4">
            Here is what 2 means
        </div>
    </div>
    <div class="row justify-content-center collapse" id="row3" data-parent="#question1">
        <div class="card card-body col-4">
            Here is what 3 means
        </div>
    </div>
    <div class="row justify-content-center collapse" id="row4" data-parent="#question1">
        <div class="card card-body col-4">
            Here is what 4 means
        </div>
    </div>
    <div class="row justify-content-center collapse" id="row5" data-parent="#question1">
        <div class="card card-body col-4">
            Here is what 5 means
        </div>
    </div>
</div>
<div class = "row justify-content-center" data-parent="#myGroup">
    <div class="col-3" style="border-bottom-style: solid;">
        Demonstrates limited/no
        personal motivation for the
        role
    </div>
    <div class="btn-group btn-group-toggle h-50" data-toggle="buttons">
        <label class="btn btn-secondary active">
            <input type="radio" name="options" id="option1" autocomplete="off"> 1
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option2" autocomplete="off"> 2
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option3" autocomplete="off"> 3
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option4" autocomplete="off"> 4
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option5" autocomplete="off"> 5
        </label>
    </div>
    <div class="col-3" style="border-bottom-style: solid;">
        Provides strong personal
        motivation for the role
    </div>
</div>
<div class = "row justify-content-center">
    <div class="col-3" style="border-bottom-style: solid;">
        Limited consideration of their
        personal fit with the role
    </div>
    <div class="btn-group btn-group-toggle h-50" data-toggle="buttons">
        <label class="btn btn-secondary active">
            <input type="radio" name="options" id="option1" autocomplete="off"> 1
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option2" autocomplete="off"> 2
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option3" autocomplete="off"> 3
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option4" autocomplete="off"> 4
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option5" autocomplete="off"> 5
        </label>
    </div>
    <div class="col-3" style="border-bottom-style: solid;">
        Demonstrates their personal fit
        (skills, qualities and
        experiences) for the role
    </div>
</div>
<div class = "row justify-content-center">
    <div class="col-3" style="border-bottom-style: solid;">
        Speaks in a hesitant or
        unconvincing manner;
        displays a lack of confidence;
        or speaks too fast and
        mumbles
    </div>
    <div class="btn-group btn-group-toggle h-50" data-toggle="buttons">
        <label class="btn btn-secondary active">
            <input type="radio" name="options" id="option1" autocomplete="off"> 1
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option2" autocomplete="off"> 2
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option3" autocomplete="off"> 3
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option4" autocomplete="off"> 4
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option5" autocomplete="off"> 5
        </label>
    </div>
    <div class="col-3" style="border-bottom-style: solid;">
        Speaks confidently and clearly
        and at a good pace
    </div>
</div>
<label>Please enter any feedback you might have for this section:</label>
<textarea class="form-control" id="exampleFormControlTextarea1" rows="4"></textarea>
<a href="#" class="btn btn-primary">Section Finished</a>
