<?php require_once("template/header.phtml")?>
<h3>Section 1 : Motivation</h3>
<h4 style="font-style: italic;">Question their motivation, level of interest and any preconceptions that they
    have. You may find the following prompt questions useful:</h4>
<ul>
    <li>Tell us about why you are interested in working in this environment?</li>
    <li>What qualities do you feel will make you a success?</li>
    <li>Is there anything that worries you about working for the Government
        (insert chosen field i.e., Engineer, Medical, HR)?
    <li>What are you looking to achieve in your career?</li>
</ul>
<br class = "container">

<div class = "row justify-content-center" data-parent="#myGroup">
    <div class="col-3" style="border-bottom-style: solid;">
        Demonstrates limited/no
        personal motivation for the
        role
    </div>
    <div class="btn-group btn-group-toggle h-50" data-toggle="buttons">
        <label class="btn btn-secondary active">
            <input type="radio" name="options" id="option1" autocomplete="off"> 1
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option2" autocomplete="off"> 2
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option3" autocomplete="off"> 3
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option4" autocomplete="off"> 4
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option5" autocomplete="off"> 5
        </label>
    </div>
    <div class="col-3" style="border-bottom-style: solid;">
        Provides strong personal
        motivation for the role
    </div>
</div>
<div class = "row justify-content-center">
    <div class="col-3" style="border-bottom-style: solid;">
        Limited consideration of their
        personal fit with the role
    </div>
    <div class="btn-group btn-group-toggle h-50" data-toggle="buttons">
        <label class="btn btn-secondary active">
            <input type="radio" name="options" id="option1" autocomplete="off"> 1
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option2" autocomplete="off"> 2
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option3" autocomplete="off"> 3
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option4" autocomplete="off"> 4
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option5" autocomplete="off"> 5
        </label>
    </div>
    <div class="col-3" style="border-bottom-style: solid;">
        Demonstrates their personal fit
        (skills, qualities and
        experiences) for the role
    </div>
</div>
<div class = "row justify-content-center">
    <div class="col-3" style="border-bottom-style: solid;">
        Speaks in a hesitant or
        unconvincing manner;
        displays a lack of confidence;
        or speaks too fast and
        mumbles
    </div>
    <div class="btn-group btn-group-toggle h-50" data-toggle="buttons">
        <label class="btn btn-secondary active">
            <input type="radio" name="options" id="option1" autocomplete="off"> 1
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option2" autocomplete="off"> 2
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option3" autocomplete="off"> 3
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option4" autocomplete="off"> 4
        </label>
        <label class="btn btn-secondary">
            <input type="radio" name="options" id="option5" autocomplete="off"> 5
        </label>
    </div>
    <div class="col-3" style="border-bottom-style: solid;">
        Speaks confidently and clearly
        and at a good pace
    </div>
</div>
<label>Please enter any feedback you might have for this section:</label>
<textarea class="form-control" id="exampleFormControlTextarea1" rows="4"></textarea>
<a href="#" class="btn btn-primary">Section Finished</a>
<?php require_once("template/footer.phtml")?>