<?php require_once("template/header.phtml"); ?>
<div class = "container">
    <?php
        if(isset($_GET['candID']))
        {
            echo '<div class = "row justify-content-center">';
            echo '<h2>Currently Creating template for '.$view->candName[0].'</h2>';
            echo '</div>';

            echo '<div class = "row justify-content-center">';
            echo '<h3>His work domain: '.$view->candDom[0].'</h3>';
            echo '</div>';

        }
        else if(isset($_COOKIE["candidateID"]))
        {
            if(!empty($_COOKIE["candidateID"]))
            {
                echo '<div class = "row justify-content-center">';
                echo '<h2>Currently Creating template for '.$view->candName[0].'</h2>';
                echo '</div>';

                echo '<div class = "row justify-content-center">';
                echo '<h3>His work domain: '.$view->candDom[0].'</h3>';
                echo '</div>';
            }
            else
            {
                echo '<div class = "row justify-content-center">';
                echo '<h2>Here you can create a template based on the information in the database</h2>';
                echo '</div>';
            }

        }
        else
        {
            echo '<div class = "row justify-content-center">';
            echo '<h2>Here you can create a template based on the information in the database</h2>';
            echo '</div>';
        }
    ?>
    <?php
        if(!empty($_COOKIE["candName"]))
        {
            echo '<div class = "d-none">';
        }
        else
            echo '<div>';
    ?>
        <form class="form-group" method = "post" action="../createTemplate.php">
            <label>Please enter candidate's name to search through all candidates</label>
            <input class="form-control" type="text" name = "candName" placeholder="Please Enter candidate name" required>
            <button type="submit" name = "search" class="btn btn-primary">Search</button>
        </form>
    </div>

    <?php
    if(empty($_COOKIE["assessmentType"]) and !empty($_COOKIE["candName"]) and !empty($_COOKIE["candidateID"]) and !empty($_COOKIE["domain"]))
    {
        echo '<div>';
    }
    else
    {
        echo '<div class = "d-none">';
    }

    ?>
        <form class="form-group" method = "post" action="../createTemplate.php">
            <label> Assessment Types:</label>
            <select name = "assessmentTypes" multiple class="form-control" required>
                <?php
                foreach($view->assessmentTy as $currentType)
                {
                    echo '<option>'.$currentType->getName(). '</option>';
                }
                ?>
            </select>
            <button type="submit" name = "selectedAssessmentType" class="btn btn-primary">Select Assessment Type</button>
        </form>
    </div>



        <?php
        if(!empty($_COOKIE["assessmentType"]) and !empty($_COOKIE["candName"]) and empty($_COOKIE["maxSections"]))
        {
            echo '<div>';
        }
        else {
            echo '<div class = "d-none">';
        }
        ?>
        <form class="form-group" method = "post" action="../createTemplate.php">
            <label>Please Enter How Many Sections you would like</label>
            <input class="form-control" min = "1" max = "10" type="number" name = "maxSections" placeholder="Please Enter Maximum section no" required>
            <button type="submit" name = "maxPost" class="btn btn-primary">Enter Maximum Sections</button>
        </form>
    </div>

    <?php
    if(!empty($_COOKIE["maxSections"]) and !isset($_SESSION["questionPerSect0"]))
    {
        echo '<div>';
    }
    else {
        echo '<div class = "d-none">';
    }
    ?>
        <form class="form-group" method = "post" action="../createTemplate.php">
            <label>Please select Which Sections You Would like added</label>
            <?php
                for($x=0;$x<$_COOKIE["maxSections"];$x++)
                {
                    echo '<input list = "section" class="form-control" type="text" name = "sectionChoose'.$x.'" placeholder="Please Enter Section" required>';
                }
                ?>
            <datalist id="section">
            <?php
                foreach($view->sections as $currentSect)
                {
                    echo '<option>'.$currentSect->getName().'</option>';
                }
            ?>
            </datalist>
            <button type="submit" name = "sectionSubmit" class="btn btn-primary">Enter</button>
        </form>
    </div>

        <?php
            if(isset($_SESSION["questionPerSect0"]) and !isset($_SESSION["maxQperSect0"]))
            {
                echo '<div>';
            }
            else
            {
                echo '<div class = "d-none">';
            }
            ?>
                <form class="form-group" method = "post" action="../createTemplate.php">
                    <?php
                    if(isset($_SESSION["questionPerSect0"]) and !isset($_SESSION["maxQperSect0"]))
                        if(isset($_COOKIE["maxSections"]))
                        {
                            for ($x = 0; $x < $_COOKIE["maxSections"]; $x++)
                            {
                                echo '<h1>'.$_SESSION["sectionHeader"][$x].'</h1>';
                                echo '<input class="form-control" min = "1" max = "10" type="number" name = "maxQuestionsPerSect' . $x . '" placeholder="Please Enter Maximum questions per section" required>';

                            }
                        }
                    ?>
                    <button type="submit" name = "maxQperSectionSubmit" class="btn btn-primary">Enter</button>
                </form>
        </div>

        <?php
        if(isset($_SESSION["questionPerSect0"]) and isset($_SESSION["maxQperSect0"]))
        {
            echo '<div>';
        }
        else
        {
            echo '<div class = "d-none">';
        }
        ?>
        <form class="form-group" method = "post" action="../createTemplate.php">
            <?php
            if(isset($_SESSION["questionPerSect0"]) and isset($_SESSION["maxQperSect0"]))
                for ($x = 0; $x < $_COOKIE["maxSections"]; $x++)
                {
                    echo '<h1>'.$_SESSION["sectionHeader"][$x].'</h1>';
                    //

                    for($y = 0; $y < (int)$_SESSION["maxQperSect".$x][0]; $y++)
                    {
                        echo '<input list = "sectionQuestions'.$x.'" class="form-control" type="text" name = "question'.$y.'PerSect' . $x . '" placeholder="Please Enter Question here" required>';
                    }
                    echo '<datalist id="sectionQuestions'.$x.'">';

                    $maxQuestions = count($_SESSION["questionPerSect".$x]);
                    for($z = 0; $z < $maxQuestions; $z++)
                    {
                        echo '<option>'.$_SESSION["questionPerSect".$x][$z].'</option>';
                    }
                    echo '</datalist>';
                }
            ?>
            <button type="submit" name = "done" class="btn btn-primary">Enter</button>
        </form>
    </div>
    <a href="../deleteCookies.php" class="btn btn-primary">Delete Cookies</a>
</div>

<?php require_once("template/footer.phtml");