<?php require_once("template/header.phtml"); ?>
<div class = "container">
    <div class = "row justify-content-center">
        <h2>Here you can create a template based on the information in the database</h2>
    </div>
    <form class="form-group" method = "post" action="../createTemplate.php">
        <label>Please enter candidate's name to search through all candidates</label>
        <input class="form-control" type="text" name = "candName" placeholder="Please Enter candidate name">
    </form>

</div>

<?php require_once("template/footer.phtml");