<?php
require_once('template/header.phtml');
?>
<div class = "container">
<?php
if($_SESSION['loggedIn']) { //php will check if user is logged in
    //echo hello username and give the user the option to logout
    echo '<h1>Here are your options based on your pre-set privileges</h1>';
    echo '<row class = "justify-content-center">
              <a href="../addToDatabaseAdmin.php" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Add Items to database</a>
              <a href="../generateFeedback.php" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Generate Feedback</a>
              <a href="../logout.php" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Logout</a>
            </row>';
    }

foreach($view->userPriv as $privilege) {
    echo 'You have a category id of : ';
    echo $privilege->getUserCategoryID();
    if($privilege->getUserCategoryID() == 1)
    {
        echo "you're an admin Harry!";
    }
    else if($privilege->getUserCategoryID() == 2)
    {
        echo "you're an admin Harry!";
    }
}
?>

</div>
<?php require_once('template/footer.phtml'); ?>