<?php require('template/header.phtml') ?>
<div class = "container">
    <h2>Insert New Indicator</h2>
    <form class="form-group" method = "post" action="../makeAssessment.php">
        <label for="sections">Select Section</label>
        <select name = "sectionName" multiple class="form-control" id="sections" onclick="this.form.submit()">
            <?php
                foreach($view->sec as $currentSection)
                {
                    echo '<option>'. $currentSection->getName(). '</option>';
                }
            ?>
        </select>
    </form>
    <form class="form-group" method = "post" action="../makeAssessment.php">
        <input class="form-control" type="text" placeholder="Insert Max Score">
        <button type="submit" name = "submitMaxScore" class="btn btn-primary">Submit</button>
    </form>
</div>

<?php require('template/footer.phtml') ?>