<?php require_once("template/header.phtml"); ?>
<div class = "container">
    <div class = "row justify-content-center">
        <h2>Here are your candidates</h2>
    </div>
    <?php
    if(isset($_COOKIE["candName"]))
        if(!empty($_COOKIE["candName"]))
        {
            if(!empty($view->candID))
            {
                foreach ($view->candID as $currentID) {
                    echo '<div>';
                    echo '<a href="../createTemplate.php?candID=' . $currentID->getID() . '">' . $currentID->getName();
                    echo '</div>';
                }
            }
        }
    if(isset($_COOKIE["candNameAssessor"]))
        if(!empty($view->candIDAssessor))
        {
            foreach ($view->candIDAssessor as $currentID) {
                echo '<div>';
                echo '<a href="../assessorView.php?candID=' . $currentID->getID() . '">' . $currentID->getName();
                echo '</div>';
            }
        }
    if(isset($_COOKIE["candNameReport"]))
        if(!empty($view->candIDReport))
        {
            foreach ($view->candIDReport as $currentID) {
                $filepath = "./candidatesFeedback/".$currentID->getID().".txt";
                if(file_exists($filepath))
                {
                    echo '<div>';
                    echo '<a href="../createReport.php?candID=' . $currentID->getID() . '">' . $currentID->getName();
                    $lines = new FeedbackGenerator();
                    $qAnswered = $lines->getLines($filepath);
                    $assessmentInfoQuery = new AssessmentInfoQueries();
                    $qToAnswer = $assessmentInfoQuery->getNumberOfQPerCandid($currentID->getID());
                    echo '<p>Has answered '.$qAnswered.'/'.$qToAnswer[0].' Questions</p>';
                    echo '</div>';
                }
            }
        }
    ?>
</div>

<?php require_once("template/footer.phtml"); ?>
