<?php require_once("template/header.phtml"); ?>
<div class = "container">
    <div class = "row justify-content-center">
        <h2>Here are your candidates</h2>
    </div>
    <?php
    if(isset($_COOKIE["candNameAssessor"]))
        if(!empty($view->candIDAssessor))
        {
            echo '<table class="table">';
            echo '<thead>';
            echo '<tr>';
            echo '<th scope="col">#</th>';
            echo '<th scope="col">Name</th>';
            echo '<th scope="col">Mark Assessment!</th>';
            echo '</tr>';
            echo '</thead>';
            echo '<tbody>';
            $row = 1;
            foreach ($view->candIDAssessor as $currentID) {
                echo '<div>';
                echo '<tr>';
                echo '<th scope = "row">'.$row.'</th>';
                echo '<td>'.$currentID->getName().'</td>';
                echo '<td><a href="../assessorView.php?candID=' . $currentID->getID() . '" class="btn btn-primary">Create Template!</a></td>';
                //echo '<a href="../assessorView.php?candID=' . $currentID->getID() . '">' . $currentID->getName();
                echo '</tr>';
                echo '</div>';
                $row++;
            }
            echo '</tbody>';
            echo '</table>';
        }
    ?>
</div>

<?php require_once("template/footer.phtml"); ?>
