<?php require_once("template/header.phtml"); ?>
<div class = "container">
    <div class = "row justify-content-center">
        <h2>Here are your candidates</h2>
    </div>
    <?php
    if(isset($_COOKIE["candNameAssessor"]))
        if(!empty($view->candIDAssessor))
        {
            foreach ($view->candIDAssessor as $currentID) {
                echo '<div>';
                echo '<a href="../assessorView.php?candID=' . $currentID->getID() . '">' . $currentID->getName();
                echo '</div>';
            }
        }
    ?>
</div>

<?php require_once("template/footer.phtml"); ?>
