    </div>


    <div>
        <div id="footer" class="fixed-bottom">
            <p>Website created by University of Salford students as part of HackCamp</p>
            <p>©Copyright: HR in One</p>
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="../../js/jquery-3.5.1.slim.js"></script>
<script src="../../js/bootstrap.bundle.js"></script>
</body>
</html>