    </div>


    <div>
        <div id="footer" class="col-xs-12">
            <p>Web-site development using the MVC design pattern and the Bootstrap CSS framework</p>
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="../../js/jquery-3.5.1.slim.js"></script>
<script src="../../js/bootstrap.js"></script>
</body>
</html>