<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <title>PACE Portal</title>
    <link type="text/css" rel="stylesheet" href="../../fpdf.css">
    <link rel="stylesheet" href="../../css/bootstrap.css">
    <link type="text/css" rel="stylesheet" href = "../../css/my-style.css">
    <!--- ReCaptcha -->
    <script src="https://www.google.com/recaptcha/api.js"></script>
    <script>
        function onSubmit(token) {
            document.getElementById("loginMain").submit();
        }
    </script>


</head>
<body>
<?php
    if(!isset($_SESSION))
    {
        session_start();
    }
?>
<nav id = "nav" class="navbar navbar-expand-lg bg-custom">
    <a class="navbar-brand" href="#">
        <img src="../../images/logoHRinOne.png" width="30" height="30" class="d-inline-block align-top" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <?php
                if(isset($_SESSION["privilege"]))
                {
                    if($_SESSION["privilege"] === "admin")
                    {
                        echo '<li class="nav-item">
                               <a class="nav-link" id = "change"  href="../../index.php">Home <span class="sr-only">(current)</span></a>
                             </li>';

                        echo '<li class="nav-item">
                                <a class="nav-link"  href="../../adminUserPage.php">Manage Staff</a>
                              </li>';

                        echo '<li class="nav-item">
                                <a class="nav-link"  href="../../addToDatabaseAdmin.php">Add to database</a>
                              </li>';


                        echo '<li class="nav-item">
                                <a class="nav-link"  href="../../createTemplate.php">Create Template</a>
                              </li>';

                        echo '<li class="nav-item">
                                <a class="nav-link"  href="../../assessorView.php">View Template</a>
                              </li>';

                        echo '<li class="nav-item">
                                <a class="nav-link"  href="../../createReport.php">Generate Feedback!</a>
                              </li>';

                        echo '<li class="nav-item">
                                 <a class="nav-link"  href="../../logout.php">Log Out</a>
                              </li>';
                    }
                    else if($_SESSION["privilege"] == "assessor")
                    {
                        echo '<li class="nav-item">
                                  <a class="nav-link" href="../../assessorView.php">View Template</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link" href="../../createReport.php">Generate Feedback!</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link" href="../../logout.php">Log Out</a>
                              </li>';
                    }
                }
                else
                {
                    echo '<li class="nav-item">
                                  <a class="nav-link" href="#">Please log in to do anything</a>
                              </li>';
                }
            ?>
        </ul>
    </div>
</nav>
