<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

require 'PHPMailer/src/Exception.php';
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';
require_once("CandidateInfoQueries.php");

/**
 * Class Mailer : Can mail candidates based on id their pace reports / instructions
 */
class Mailer
{

    /**
     * Function that will take an autogenerated pdf report and mail it to a candidate based on id
     * @param $candidateID
     */
    function mailCandidate($candidateID)
    {
        $mail = new PHPMailer(true);
        $candidateQuery = new CandidateInfoQueries();

        try {
            //Server settings
            // CHANGE THIS BEFORE LIVE DEPLYMENT
            $mail->isSMTP();                                            // Send using SMTP
            $mail->Host       = 'smtp.gmail.com';                    // Set the SMTP server to send through
            $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
            $mail->Username   = 'br588427@gmail.com';                     // SMTP username
            $mail->Password   = 'aPassword123';                          // SMTP password
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;         // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged
            $mail->Port       = 587;                                    // TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above

            $candidateEmail = $candidateQuery->getCandidateEmail($candidateID); // get candidates email
            //Recipients
            $mail->setFrom('whoSentDis@gmail.com', 'Who knows'); //name of the sent from address
            $mail->addAddress($candidateEmail[0]);     // Add a recipient


            // Attachments
            $filename = './tempRep/'.$candidateID.'.pdf'; //directory to our temp storage for the pdfs

            if(file_exists($filename))
            {
                $mail->addAttachment($filename, 'PACEReport.pdf'); // we add the attachment here
            }
            $mail->isHTML(true); // Set email format to HTML
            $mail->Subject = 'Your PACE Report!'; //subject
            $mail->Body    = 'Below you can find the pace report attached :)';
            $mail->AltBody = 'Below you can find the pace report attached :)'; // if html format doesnt work use this

            $mail->send();
            if(file_exists($filename))
            {
                unlink($filename); //delete pdf after its sent
            }
        } catch (Exception $e) {
            echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
        }
    }
}
